{
    "expected": [
        {
            "@timestamp": "2022-03-03T11:37:34.933Z",
            "cisco_ise": {
                "log": {
                    "acs": {
                        "session": {
                            "id": "cisco-ise-host/435083133/126"
                        }
                    },
                    "authentication": {
                        "method": "Lookup"
                    },
                    "category": {
                        "name": "CISE_Identity_Stores_Diagnostics"
                    },
                    "config_version": {
                        "id": 1696
                    },
                    "cpm": {
                        "session": {
                            "id": "0a0009ccdD2BsLZMkW8ZRUAE/sDVf78pplxJC0wv2VwZR6N070M"
                        }
                    },
                    "message": {
                        "code": "24209",
                        "description": "Local-user-DB: Looking up Endpoint in Internal Endpoints IDStore",
                        "id": "0000083418"
                    },
                    "original": {
                        "user": {
                            "name": "92-09-00-00-00-01"
                        }
                    },
                    "response": {
                        "AuthenticationResult": "UnknownUser",
                        "QueryResult": "UnknownUser"
                    },
                    "segment": {
                        "number": 0,
                        "total": 1
                    },
                    "selected": {
                        "access": {
                            "service": "Default Network Access"
                        }
                    }
                }
            },
            "ecs": {
                "version": "8.10.0"
            },
            "event": {
                "action": "local-user-db",
                "category": [
                    "iam",
                    "malware"
                ],
                "code": "24209",
                "kind": "event",
                "original": "\u003c183\u003eMar 3 11:37:34 cisco-ise-host CISE_Identity_Stores_Diagnostics 0000083418 1 0 2022-03-03 11:37:34.933 +00:00 0000083485 24209 DEBUG Local-user-DB: Looking up Endpoint in Internal Endpoints IDStore, ConfigVersionId=1696, UserName=92-09-00-00-00-01, Protocol=Radius, OriginalUserName=92-09-00-00-00-01, AcsSessionID=cisco-ise-host/435083133/126, AuthenticationMethod=Lookup, SelectedAccessService=Default Network Access, CPMSessionID=0a0009ccdD2BsLZMkW8ZRUAE/sDVf78pplxJC0wv2VwZR6N070M, Response={AuthenticationResult=UnknownUser; QueryResult=UnknownUser; },",
                "sequence": 83485,
                "timezone": "+00:00",
                "type": [
                    "info"
                ]
            },
            "host": {
                "hostname": "cisco-ise-host"
            },
            "log": {
                "level": "debug",
                "syslog": {
                    "priority": 183,
                    "severity": {
                        "name": "debug"
                    }
                }
            },
            "message": "2022-03-03 11:37:34.933 +00:00 0000083485 24209 DEBUG Local-user-DB: Looking up Endpoint in Internal Endpoints IDStore, ConfigVersionId=1696, UserName=92-09-00-00-00-01, Protocol=Radius, OriginalUserName=92-09-00-00-00-01, AcsSessionID=cisco-ise-host/435083133/126, AuthenticationMethod=Lookup, SelectedAccessService=Default Network Access, CPMSessionID=0a0009ccdD2BsLZMkW8ZRUAE/sDVf78pplxJC0wv2VwZR6N070M, Response={AuthenticationResult=UnknownUser; QueryResult=UnknownUser; },",
            "network": {
                "protocol": "radius"
            },
            "related": {
                "hosts": [
                    "cisco-ise-host"
                ],
                "user": [
                    "92-09-00-00-00-01"
                ]
            },
            "tags": [
                "preserve_original_event"
            ],
            "user": {
                "name": "92-09-00-00-00-01"
            }
        },
        {
            "@timestamp": "2022-03-03T09:24:13.235Z",
            "cisco_ise": {
                "log": {
                    "acs": {
                        "session": {
                            "id": "cisco-ise-host/435083133/115"
                        }
                    },
                    "authentication": {
                        "method": "PAP_ASCII"
                    },
                    "category": {
                        "name": "CISE_Identity_Stores_Diagnostics"
                    },
                    "config_version": {
                        "id": 1628
                    },
                    "cpm": {
                        "session": {
                            "id": "cisco-ise-host:userauth20"
                        }
                    },
                    "currentid": {
                        "store_name": "Internal Users"
                    },
                    "message": {
                        "code": "24210",
                        "description": "Local-user-DB: Looking up User in Internal Users IDStore",
                        "id": "0000082649"
                    },
                    "segment": {
                        "number": 0,
                        "total": 1
                    },
                    "selected": {
                        "access": {
                            "service": "AuthenticateUserAPI"
                        }
                    }
                }
            },
            "ecs": {
                "version": "8.10.0"
            },
            "event": {
                "action": "local-user-db",
                "category": [
                    "iam"
                ],
                "code": "24210",
                "kind": "event",
                "original": "\u003c183\u003eMar 3 09:24:13 cisco-ise-host CISE_Identity_Stores_Diagnostics 0000082649 1 0 2022-03-03 09:24:13.235 +00:00 0000082716 24210 DEBUG Local-user-DB: Looking up User in Internal Users IDStore, ConfigVersionId=1628, UserName=test, SelectedAccessService=AuthenticateUserAPI, AcsSessionID=cisco-ise-host/435083133/115, AuthenticationMethod=PAP_ASCII, CurrentIDStoreName=Internal Users, CPMSessionID=cisco-ise-host:userauth20,",
                "sequence": 82716,
                "timezone": "+00:00",
                "type": [
                    "info",
                    "user"
                ]
            },
            "host": {
                "hostname": "cisco-ise-host"
            },
            "log": {
                "level": "debug",
                "syslog": {
                    "priority": 183,
                    "severity": {
                        "name": "debug"
                    }
                }
            },
            "message": "2022-03-03 09:24:13.235 +00:00 0000082716 24210 DEBUG Local-user-DB: Looking up User in Internal Users IDStore, ConfigVersionId=1628, UserName=test, SelectedAccessService=AuthenticateUserAPI, AcsSessionID=cisco-ise-host/435083133/115, AuthenticationMethod=PAP_ASCII, CurrentIDStoreName=Internal Users, CPMSessionID=cisco-ise-host:userauth20,",
            "related": {
                "hosts": [
                    "cisco-ise-host"
                ],
                "user": [
                    "test"
                ]
            },
            "tags": [
                "preserve_original_event"
            ],
            "user": {
                "name": "test"
            }
        },
        {
            "@timestamp": "2022-03-03T09:22:51.639Z",
            "cisco_ise": {
                "log": {
                    "acs": {
                        "session": {
                            "id": "cisco-ise-host/435083133/110"
                        }
                    },
                    "authentication": {
                        "method": "PAP_ASCII"
                    },
                    "category": {
                        "name": "CISE_Identity_Stores_Diagnostics"
                    },
                    "config_version": {
                        "id": 1628
                    },
                    "cpm": {
                        "session": {
                            "id": "cisco-ise-host:userauth18"
                        }
                    },
                    "currentid": {
                        "store_name": "Internal Users"
                    },
                    "enable": {
                        "flag": "Enabled"
                    },
                    "message": {
                        "code": "24212",
                        "description": "Local-user-DB: Found User in Internal Users IDStore",
                        "id": "0000082604"
                    },
                    "response": {
                        "AuthenticationResult": "NotPerformed"
                    },
                    "segment": {
                        "number": 0,
                        "total": 1
                    },
                    "selected": {
                        "access": {
                            "service": "AuthenticateUserAPI"
                        }
                    }
                }
            },
            "ecs": {
                "version": "8.10.0"
            },
            "event": {
                "action": "local-user-db",
                "category": [
                    "iam"
                ],
                "code": "24212",
                "kind": "event",
                "original": "\u003c183\u003eMar 3 09:22:51 cisco-ise-host CISE_Identity_Stores_Diagnostics 0000082604 1 0 2022-03-03 09:22:51.639 +00:00 0000082671 24212 DEBUG Local-user-DB: Found User in Internal Users IDStore, ConfigVersionId=1628, UserName=employee1, SelectedAccessService=AuthenticateUserAPI, AcsSessionID=cisco-ise-host/435083133/110, AuthenticationMethod=PAP_ASCII, CurrentIDStoreName=Internal Users, CPMSessionID=cisco-ise-host:userauth18, Firstname=Employee1, Lastname=Cisco1, EnableFlag=Enabled, Response={AuthenticationResult=NotPerformed; },",
                "sequence": 82671,
                "timezone": "+00:00",
                "type": [
                    "info",
                    "user"
                ]
            },
            "host": {
                "hostname": "cisco-ise-host"
            },
            "log": {
                "level": "debug",
                "syslog": {
                    "priority": 183,
                    "severity": {
                        "name": "debug"
                    }
                }
            },
            "message": "2022-03-03 09:22:51.639 +00:00 0000082671 24212 DEBUG Local-user-DB: Found User in Internal Users IDStore, ConfigVersionId=1628, UserName=employee1, SelectedAccessService=AuthenticateUserAPI, AcsSessionID=cisco-ise-host/435083133/110, AuthenticationMethod=PAP_ASCII, CurrentIDStoreName=Internal Users, CPMSessionID=cisco-ise-host:userauth18, Firstname=Employee1, Lastname=Cisco1, EnableFlag=Enabled, Response={AuthenticationResult=NotPerformed; },",
            "related": {
                "hosts": [
                    "cisco-ise-host"
                ],
                "user": [
                    "employee1",
                    "Employee1",
                    "Cisco1",
                    "Employee1 Cisco1"
                ]
            },
            "tags": [
                "preserve_original_event"
            ],
            "user": {
                "full_name": "Employee1 Cisco1",
                "name": "employee1"
            }
        },
        {
            "@timestamp": "2022-03-03T09:22:59.336Z",
            "cisco_ise": {
                "log": {
                    "acs": {
                        "session": {
                            "id": "cisco-ise-host/435083133/112"
                        }
                    },
                    "authentication": {
                        "method": "PAP_ASCII"
                    },
                    "category": {
                        "name": "CISE_Identity_Stores_Diagnostics"
                    },
                    "config_version": {
                        "id": 1628
                    },
                    "cpm": {
                        "session": {
                            "id": "cisco-ise-host:userauth19"
                        }
                    },
                    "currentid": {
                        "store_name": "Internal Users"
                    },
                    "message": {
                        "code": "24216",
                        "description": "Local-user-DB: The user is not found in the internal users identity store",
                        "id": "0000082616"
                    },
                    "response": {
                        "AuthenticationResult": "UnknownUser",
                        "LdapOperationStatus": "SubjectNotFound"
                    },
                    "segment": {
                        "number": 0,
                        "total": 1
                    },
                    "selected": {
                        "access": {
                            "service": "AuthenticateUserAPI"
                        }
                    }
                }
            },
            "ecs": {
                "version": "8.10.0"
            },
            "event": {
                "action": "local-user-db",
                "category": [
                    "iam"
                ],
                "code": "24216",
                "kind": "event",
                "original": "\u003c183\u003eMar 3 09:22:59 cisco-ise-host CISE_Identity_Stores_Diagnostics 0000082616 1 0 2022-03-03 09:22:59.336 +00:00 0000082683 24216 DEBUG Local-user-DB: The user is not found in the internal users identity store, ConfigVersionId=1628, UserName=admin, SelectedAccessService=AuthenticateUserAPI, AcsSessionID=cisco-ise-host/435083133/112, AuthenticationMethod=PAP_ASCII, CurrentIDStoreName=Internal Users, CPMSessionID=cisco-ise-host:userauth19, Response={AuthenticationResult=UnknownUser; LdapOperationStatus=SubjectNotFound; },",
                "sequence": 82683,
                "timezone": "+00:00",
                "type": [
                    "info",
                    "user"
                ]
            },
            "host": {
                "hostname": "cisco-ise-host"
            },
            "log": {
                "level": "debug",
                "syslog": {
                    "priority": 183,
                    "severity": {
                        "name": "debug"
                    }
                }
            },
            "message": "2022-03-03 09:22:59.336 +00:00 0000082683 24216 DEBUG Local-user-DB: The user is not found in the internal users identity store, ConfigVersionId=1628, UserName=admin, SelectedAccessService=AuthenticateUserAPI, AcsSessionID=cisco-ise-host/435083133/112, AuthenticationMethod=PAP_ASCII, CurrentIDStoreName=Internal Users, CPMSessionID=cisco-ise-host:userauth19, Response={AuthenticationResult=UnknownUser; LdapOperationStatus=SubjectNotFound; },",
            "related": {
                "hosts": [
                    "cisco-ise-host"
                ],
                "user": [
                    "admin"
                ]
            },
            "tags": [
                "preserve_original_event"
            ],
            "user": {
                "name": "admin"
            }
        },
        {
            "@timestamp": "2022-03-03T11:37:34.936Z",
            "cisco_ise": {
                "log": {
                    "acs": {
                        "session": {
                            "id": "cisco-ise-host/435083133/126"
                        }
                    },
                    "authentication": {
                        "method": "Lookup"
                    },
                    "category": {
                        "name": "CISE_Identity_Stores_Diagnostics"
                    },
                    "config_version": {
                        "id": 1696
                    },
                    "cpm": {
                        "session": {
                            "id": "0a0009ccdD2BsLZMkW8ZRUAE/sDVf78pplxJC0wv2VwZR6N070M"
                        }
                    },
                    "message": {
                        "code": "24217",
                        "description": "Local-user-DB: The host is not found in the internal endpoints identity store",
                        "id": "0000083419"
                    },
                    "original": {
                        "user": {
                            "name": "92-09-00-00-00-01"
                        }
                    },
                    "response": {
                        "AuthenticationResult": "UnknownUser",
                        "QueryResult": "UnknownUser"
                    },
                    "segment": {
                        "number": 0,
                        "total": 1
                    },
                    "selected": {
                        "access": {
                            "service": "Default Network Access"
                        }
                    }
                }
            },
            "ecs": {
                "version": "8.10.0"
            },
            "event": {
                "action": "local-user-db",
                "category": [
                    "iam",
                    "host"
                ],
                "code": "24217",
                "kind": "event",
                "original": "\u003c183\u003eMar 3 11:37:34 cisco-ise-host CISE_Identity_Stores_Diagnostics 0000083419 1 0 2022-03-03 11:37:34.936 +00:00 0000083486 24217 DEBUG Local-user-DB: The host is not found in the internal endpoints identity store, ConfigVersionId=1696, UserName=92-09-00-00-00-01, Protocol=Radius, OriginalUserName=92-09-00-00-00-01, AcsSessionID=cisco-ise-host/435083133/126, AuthenticationMethod=Lookup, SelectedAccessService=Default Network Access, CPMSessionID=0a0009ccdD2BsLZMkW8ZRUAE/sDVf78pplxJC0wv2VwZR6N070M, Response={AuthenticationResult=UnknownUser; QueryResult=UnknownUser; },",
                "sequence": 83486,
                "timezone": "+00:00",
                "type": [
                    "info"
                ]
            },
            "host": {
                "hostname": "cisco-ise-host"
            },
            "log": {
                "level": "debug",
                "syslog": {
                    "priority": 183,
                    "severity": {
                        "name": "debug"
                    }
                }
            },
            "message": "2022-03-03 11:37:34.936 +00:00 0000083486 24217 DEBUG Local-user-DB: The host is not found in the internal endpoints identity store, ConfigVersionId=1696, UserName=92-09-00-00-00-01, Protocol=Radius, OriginalUserName=92-09-00-00-00-01, AcsSessionID=cisco-ise-host/435083133/126, AuthenticationMethod=Lookup, SelectedAccessService=Default Network Access, CPMSessionID=0a0009ccdD2BsLZMkW8ZRUAE/sDVf78pplxJC0wv2VwZR6N070M, Response={AuthenticationResult=UnknownUser; QueryResult=UnknownUser; },",
            "network": {
                "protocol": "radius"
            },
            "related": {
                "hosts": [
                    "cisco-ise-host"
                ],
                "user": [
                    "92-09-00-00-00-01"
                ]
            },
            "tags": [
                "preserve_original_event"
            ],
            "user": {
                "name": "92-09-00-00-00-01"
            }
        },
        {
            "@timestamp": "2022-03-03T09:22:59.359Z",
            "cisco_ise": {
                "log": {
                    "ad": {
                        "log_id": "1645524126/33"
                    },
                    "category": {
                        "name": "CISE_Identity_Stores_Diagnostics"
                    },
                    "message": {
                        "code": "24313",
                        "description": "External-Active-Directory: Search for matching accounts at join point",
                        "id": "0000082623"
                    },
                    "segment": {
                        "number": 0,
                        "total": 1
                    }
                }
            },
            "ecs": {
                "version": "8.10.0"
            },
            "event": {
                "action": "external-active-directory",
                "category": [
                    "iam",
                    "authentication"
                ],
                "code": "24313",
                "kind": "event",
                "original": "\u003c183\u003eMar 3 09:22:59 cisco-ise-host CISE_Identity_Stores_Diagnostics 0000082623 1 0 2022-03-03 09:22:59.359 +00:00 0000082690 24313 DEBUG External-Active-Directory: Search for matching accounts at join point, AD-Log-Id=1645524126/33,",
                "sequence": 82690,
                "timezone": "+00:00",
                "type": [
                    "info"
                ]
            },
            "host": {
                "hostname": "cisco-ise-host"
            },
            "log": {
                "level": "debug",
                "syslog": {
                    "priority": 183,
                    "severity": {
                        "name": "debug"
                    }
                }
            },
            "message": "2022-03-03 09:22:59.359 +00:00 0000082690 24313 DEBUG External-Active-Directory: Search for matching accounts at join point, AD-Log-Id=1645524126/33,",
            "related": {
                "hosts": [
                    "cisco-ise-host"
                ]
            },
            "tags": [
                "preserve_original_event"
            ]
        },
        {
            "@timestamp": "2022-03-03T09:22:59.359Z",
            "cisco_ise": {
                "log": {
                    "ad": {
                        "log_id": "1645524126/35"
                    },
                    "category": {
                        "name": "CISE_Identity_Stores_Diagnostics"
                    },
                    "message": {
                        "code": "24322",
                        "description": "External-Active-Directory: Identity resolution detected no matching account",
                        "id": "0000082625"
                    },
                    "segment": {
                        "number": 0,
                        "total": 1
                    }
                }
            },
            "ecs": {
                "version": "8.10.0"
            },
            "event": {
                "action": "external-active-directory",
                "category": [
                    "iam",
                    "authentication"
                ],
                "code": "24322",
                "kind": "event",
                "original": "\u003c183\u003eMar 3 09:22:59 cisco-ise-host CISE_Identity_Stores_Diagnostics 0000082625 1 0 2022-03-03 09:22:59.359 +00:00 0000082692 24322 DEBUG External-Active-Directory: Identity resolution detected no matching account, AD-Log-Id=1645524126/35,",
                "sequence": 82692,
                "timezone": "+00:00",
                "type": [
                    "info"
                ]
            },
            "host": {
                "hostname": "cisco-ise-host"
            },
            "log": {
                "level": "debug",
                "syslog": {
                    "priority": 183,
                    "severity": {
                        "name": "debug"
                    }
                }
            },
            "message": "2022-03-03 09:22:59.359 +00:00 0000082692 24322 DEBUG External-Active-Directory: Identity resolution detected no matching account, AD-Log-Id=1645524126/35,",
            "related": {
                "hosts": [
                    "cisco-ise-host"
                ]
            },
            "tags": [
                "preserve_original_event"
            ]
        },
        {
            "@timestamp": "2022-03-03T09:22:59.359Z",
            "cisco_ise": {
                "log": {
                    "ad": {
                        "log_id": "1645524126/32"
                    },
                    "category": {
                        "name": "CISE_Identity_Stores_Diagnostics"
                    },
                    "message": {
                        "code": "24325",
                        "description": "External-Active-Directory: Resolving identity",
                        "id": "0000082622"
                    },
                    "segment": {
                        "number": 0,
                        "total": 1
                    }
                }
            },
            "ecs": {
                "version": "8.10.0"
            },
            "event": {
                "action": "external-active-directory",
                "category": [
                    "iam",
                    "authentication"
                ],
                "code": "24325",
                "kind": "event",
                "original": "\u003c183\u003eMar 3 09:22:59 cisco-ise-host CISE_Identity_Stores_Diagnostics 0000082622 1 0 2022-03-03 09:22:59.359 +00:00 0000082689 24325 DEBUG External-Active-Directory: Resolving identity, AD-Log-Id=1645524126/32,",
                "sequence": 82689,
                "timezone": "+00:00",
                "type": [
                    "info"
                ]
            },
            "host": {
                "hostname": "cisco-ise-host"
            },
            "log": {
                "level": "debug",
                "syslog": {
                    "priority": 183,
                    "severity": {
                        "name": "debug"
                    }
                }
            },
            "message": "2022-03-03 09:22:59.359 +00:00 0000082689 24325 DEBUG External-Active-Directory: Resolving identity, AD-Log-Id=1645524126/32,",
            "related": {
                "hosts": [
                    "cisco-ise-host"
                ]
            },
            "tags": [
                "preserve_original_event"
            ]
        },
        {
            "@timestamp": "2022-03-03T09:22:59.359Z",
            "cisco_ise": {
                "log": {
                    "ad": {
                        "log_id": "1645524126/36"
                    },
                    "category": {
                        "name": "CISE_Identity_Stores_Diagnostics"
                    },
                    "message": {
                        "code": "24352",
                        "description": "External-Active-Directory: Identity resolution failed",
                        "id": "0000082626"
                    },
                    "segment": {
                        "number": 0,
                        "total": 1
                    }
                }
            },
            "ecs": {
                "version": "8.10.0"
            },
            "event": {
                "action": "external-active-directory",
                "category": [
                    "iam",
                    "authentication"
                ],
                "code": "24352",
                "kind": "event",
                "original": "\u003c183\u003eMar 3 09:22:59 cisco-ise-host CISE_Identity_Stores_Diagnostics 0000082626 1 0 2022-03-03 09:22:59.359 +00:00 0000082693 24352 DEBUG External-Active-Directory: Identity resolution failed, AD-Log-Id=1645524126/36,",
                "sequence": 82693,
                "timezone": "+00:00",
                "type": [
                    "info",
                    "end"
                ]
            },
            "host": {
                "hostname": "cisco-ise-host"
            },
            "log": {
                "level": "debug",
                "syslog": {
                    "priority": 183,
                    "severity": {
                        "name": "debug"
                    }
                }
            },
            "message": "2022-03-03 09:22:59.359 +00:00 0000082693 24352 DEBUG External-Active-Directory: Identity resolution failed, AD-Log-Id=1645524126/36,",
            "related": {
                "hosts": [
                    "cisco-ise-host"
                ]
            },
            "tags": [
                "preserve_original_event"
            ]
        },
        {
            "@timestamp": "2022-03-03T09:22:59.359Z",
            "cisco_ise": {
                "log": {
                    "ad": {
                        "log_id": "1645524126/34"
                    },
                    "category": {
                        "name": "CISE_Identity_Stores_Diagnostics"
                    },
                    "message": {
                        "code": "24366",
                        "description": "External-Active-Directory: Skipping unjoined domain",
                        "id": "0000082624"
                    },
                    "segment": {
                        "number": 0,
                        "total": 1
                    }
                }
            },
            "ecs": {
                "version": "8.10.0"
            },
            "event": {
                "action": "external-active-directory",
                "category": [
                    "iam"
                ],
                "code": "24366",
                "kind": "event",
                "original": "\u003c183\u003eMar 3 09:22:59 cisco-ise-host CISE_Identity_Stores_Diagnostics 0000082624 1 0 2022-03-03 09:22:59.359 +00:00 0000082691 24366 DEBUG External-Active-Directory: Skipping unjoined domain, AD-Log-Id=1645524126/34,",
                "sequence": 82691,
                "timezone": "+00:00",
                "type": [
                    "info"
                ]
            },
            "host": {
                "hostname": "cisco-ise-host"
            },
            "log": {
                "level": "debug",
                "syslog": {
                    "priority": 183,
                    "severity": {
                        "name": "debug"
                    }
                }
            },
            "message": "2022-03-03 09:22:59.359 +00:00 0000082691 24366 DEBUG External-Active-Directory: Skipping unjoined domain, AD-Log-Id=1645524126/34,",
            "related": {
                "hosts": [
                    "cisco-ise-host"
                ]
            },
            "tags": [
                "preserve_original_event"
            ]
        },
        {
            "@timestamp": "2022-03-03T09:22:59.360Z",
            "cisco_ise": {
                "log": {
                    "acs": {
                        "session": {
                            "id": "cisco-ise-host/435083133/112"
                        }
                    },
                    "authentication": {
                        "method": "PAP_ASCII"
                    },
                    "category": {
                        "name": "CISE_Identity_Stores_Diagnostics"
                    },
                    "config_version": {
                        "id": 1628
                    },
                    "cpm": {
                        "session": {
                            "id": "cisco-ise-host:userauth19"
                        }
                    },
                    "currentid": {
                        "store_name": "All_AD_Join_Points"
                    },
                    "message": {
                        "code": "24412",
                        "description": "External-Active-Directory: User not found in Active Directory",
                        "id": "0000082627"
                    },
                    "response": {
                        "AuthenticationResult": "UnknownUser"
                    },
                    "segment": {
                        "number": 0,
                        "total": 1
                    },
                    "selected": {
                        "access": {
                            "service": "AuthenticateUserAPI"
                        }
                    }
                }
            },
            "ecs": {
                "version": "8.10.0"
            },
            "event": {
                "action": "external-active-directory",
                "category": [
                    "iam",
                    "authentication"
                ],
                "code": "24412",
                "kind": "event",
                "original": "\u003c183\u003eMar 3 09:22:59 cisco-ise-host CISE_Identity_Stores_Diagnostics 0000082627 1 0 2022-03-03 09:22:59.360 +00:00 0000082694 24412 DEBUG External-Active-Directory: User not found in Active Directory, ConfigVersionId=1628, UserName=admin, SelectedAccessService=AuthenticateUserAPI, AcsSessionID=cisco-ise-host/435083133/112, AuthenticationMethod=PAP_ASCII, CurrentIDStoreName=All_AD_Join_Points, CPMSessionID=cisco-ise-host:userauth19, Response={AuthenticationResult=UnknownUser; },",
                "sequence": 82694,
                "timezone": "+00:00",
                "type": [
                    "info",
                    "end"
                ]
            },
            "host": {
                "hostname": "cisco-ise-host"
            },
            "log": {
                "level": "debug",
                "syslog": {
                    "priority": 183,
                    "severity": {
                        "name": "debug"
                    }
                }
            },
            "message": "2022-03-03 09:22:59.360 +00:00 0000082694 24412 DEBUG External-Active-Directory: User not found in Active Directory, ConfigVersionId=1628, UserName=admin, SelectedAccessService=AuthenticateUserAPI, AcsSessionID=cisco-ise-host/435083133/112, AuthenticationMethod=PAP_ASCII, CurrentIDStoreName=All_AD_Join_Points, CPMSessionID=cisco-ise-host:userauth19, Response={AuthenticationResult=UnknownUser; },",
            "related": {
                "hosts": [
                    "cisco-ise-host"
                ],
                "user": [
                    "admin"
                ]
            },
            "tags": [
                "preserve_original_event"
            ],
            "user": {
                "name": "admin"
            }
        },
        {
            "@timestamp": "2022-03-03T09:22:59.357Z",
            "cisco_ise": {
                "log": {
                    "acs": {
                        "session": {
                            "id": "cisco-ise-host/435083133/112"
                        }
                    },
                    "authentication": {
                        "method": "PAP_ASCII"
                    },
                    "category": {
                        "name": "CISE_Identity_Stores_Diagnostics"
                    },
                    "config_version": {
                        "id": 1628
                    },
                    "cpm": {
                        "session": {
                            "id": "cisco-ise-host:userauth19"
                        }
                    },
                    "currentid": {
                        "store_name": "All_AD_Join_Points"
                    },
                    "message": {
                        "code": "24430",
                        "description": "External-Active-Directory: Authenticating user against Active Directory",
                        "id": "0000082621"
                    },
                    "response": {
                        "AuthenticationResult": "Failed"
                    },
                    "segment": {
                        "number": 0,
                        "total": 1
                    },
                    "selected": {
                        "access": {
                            "service": "AuthenticateUserAPI"
                        }
                    }
                }
            },
            "ecs": {
                "version": "8.10.0"
            },
            "event": {
                "action": "external-active-directory",
                "category": [
                    "iam",
                    "authentication"
                ],
                "code": "24430",
                "kind": "event",
                "original": "\u003c183\u003eMar 3 09:22:59 cisco-ise-host CISE_Identity_Stores_Diagnostics 0000082621 1 0 2022-03-03 09:22:59.357 +00:00 0000082688 24430 DEBUG External-Active-Directory: Authenticating user against Active Directory, ConfigVersionId=1628, UserName=admin, SelectedAccessService=AuthenticateUserAPI, AcsSessionID=cisco-ise-host/435083133/112, AuthenticationMethod=PAP_ASCII, CurrentIDStoreName=All_AD_Join_Points, CPMSessionID=cisco-ise-host:userauth19, Response={AuthenticationResult=Failed; },",
                "sequence": 82688,
                "timezone": "+00:00",
                "type": [
                    "info"
                ]
            },
            "host": {
                "hostname": "cisco-ise-host"
            },
            "log": {
                "level": "debug",
                "syslog": {
                    "priority": 183,
                    "severity": {
                        "name": "debug"
                    }
                }
            },
            "message": "2022-03-03 09:22:59.357 +00:00 0000082688 24430 DEBUG External-Active-Directory: Authenticating user against Active Directory, ConfigVersionId=1628, UserName=admin, SelectedAccessService=AuthenticateUserAPI, AcsSessionID=cisco-ise-host/435083133/112, AuthenticationMethod=PAP_ASCII, CurrentIDStoreName=All_AD_Join_Points, CPMSessionID=cisco-ise-host:userauth19, Response={AuthenticationResult=Failed; },",
            "related": {
                "hosts": [
                    "cisco-ise-host"
                ],
                "user": [
                    "admin"
                ]
            },
            "tags": [
                "preserve_original_event"
            ],
            "user": {
                "name": "admin"
            }
        },
        {
            "@timestamp": "2022-03-03T09:22:59.337Z",
            "cisco_ise": {
                "log": {
                    "acs": {
                        "session": {
                            "id": "cisco-ise-host/435083133/112"
                        }
                    },
                    "authentication": {
                        "method": "PAP_ASCII"
                    },
                    "category": {
                        "name": "CISE_Identity_Stores_Diagnostics"
                    },
                    "config_version": {
                        "id": 1628
                    },
                    "cpm": {
                        "session": {
                            "id": "cisco-ise-host:userauth19"
                        }
                    },
                    "currentid": {
                        "store_name": "Guest Users"
                    },
                    "message": {
                        "code": "24631",
                        "description": "Local-user-DB: Looking up User in Internal Guests IDStore",
                        "id": "0000082618"
                    },
                    "response": {
                        "AuthenticationResult": "UnknownUser"
                    },
                    "segment": {
                        "number": 0,
                        "total": 1
                    },
                    "selected": {
                        "access": {
                            "service": "AuthenticateUserAPI"
                        }
                    }
                }
            },
            "ecs": {
                "version": "8.10.0"
            },
            "event": {
                "action": "local-user-db",
                "category": [
                    "iam"
                ],
                "code": "24631",
                "kind": "event",
                "original": "\u003c183\u003eMar 3 09:22:59 cisco-ise-host CISE_Identity_Stores_Diagnostics 0000082618 1 0 2022-03-03 09:22:59.337 +00:00 0000082685 24631 DEBUG Local-user-DB: Looking up User in Internal Guests IDStore, ConfigVersionId=1628, UserName=admin, SelectedAccessService=AuthenticateUserAPI, AcsSessionID=cisco-ise-host/435083133/112, AuthenticationMethod=PAP_ASCII, CurrentIDStoreName=Guest Users, CPMSessionID=cisco-ise-host:userauth19, Response={AuthenticationResult=UnknownUser; },",
                "sequence": 82685,
                "timezone": "+00:00",
                "type": [
                    "info",
                    "user"
                ]
            },
            "host": {
                "hostname": "cisco-ise-host"
            },
            "log": {
                "level": "debug",
                "syslog": {
                    "priority": 183,
                    "severity": {
                        "name": "debug"
                    }
                }
            },
            "message": "2022-03-03 09:22:59.337 +00:00 0000082685 24631 DEBUG Local-user-DB: Looking up User in Internal Guests IDStore, ConfigVersionId=1628, UserName=admin, SelectedAccessService=AuthenticateUserAPI, AcsSessionID=cisco-ise-host/435083133/112, AuthenticationMethod=PAP_ASCII, CurrentIDStoreName=Guest Users, CPMSessionID=cisco-ise-host:userauth19, Response={AuthenticationResult=UnknownUser; },",
            "related": {
                "hosts": [
                    "cisco-ise-host"
                ],
                "user": [
                    "admin"
                ]
            },
            "tags": [
                "preserve_original_event"
            ],
            "user": {
                "name": "admin"
            }
        },
        {
            "@timestamp": "2022-03-03T09:22:59.356Z",
            "cisco_ise": {
                "log": {
                    "acs": {
                        "session": {
                            "id": "cisco-ise-host/435083133/112"
                        }
                    },
                    "authentication": {
                        "method": "PAP_ASCII"
                    },
                    "category": {
                        "name": "CISE_Identity_Stores_Diagnostics"
                    },
                    "config_version": {
                        "id": 1628
                    },
                    "cpm": {
                        "session": {
                            "id": "cisco-ise-host:userauth19"
                        }
                    },
                    "currentid": {
                        "store_name": "Guest Users"
                    },
                    "message": {
                        "code": "24633",
                        "description": "Local-user-DB: The user is not found in the internal guests identity store",
                        "id": "0000082619"
                    },
                    "response": {
                        "AuthenticationResult": "UnknownUser",
                        "LdapOperationStatus": "SubjectNotFound"
                    },
                    "segment": {
                        "number": 0,
                        "total": 1
                    },
                    "selected": {
                        "access": {
                            "service": "AuthenticateUserAPI"
                        }
                    }
                }
            },
            "ecs": {
                "version": "8.10.0"
            },
            "event": {
                "action": "local-user-db",
                "category": [
                    "iam",
                    "authentication"
                ],
                "code": "24633",
                "kind": "event",
                "original": "\u003c183\u003eMar 3 09:22:59 cisco-ise-host CISE_Identity_Stores_Diagnostics 0000082619 1 0 2022-03-03 09:22:59.356 +00:00 0000082686 24633 DEBUG Local-user-DB: The user is not found in the internal guests identity store, ConfigVersionId=1628, UserName=admin, SelectedAccessService=AuthenticateUserAPI, AcsSessionID=cisco-ise-host/435083133/112, AuthenticationMethod=PAP_ASCII, CurrentIDStoreName=Guest Users, CPMSessionID=cisco-ise-host:userauth19, Response={AuthenticationResult=UnknownUser; LdapOperationStatus=SubjectNotFound; },",
                "sequence": 82686,
                "timezone": "+00:00",
                "type": [
                    "info",
                    "end"
                ]
            },
            "host": {
                "hostname": "cisco-ise-host"
            },
            "log": {
                "level": "debug",
                "syslog": {
                    "priority": 183,
                    "severity": {
                        "name": "debug"
                    }
                }
            },
            "message": "2022-03-03 09:22:59.356 +00:00 0000082686 24633 DEBUG Local-user-DB: The user is not found in the internal guests identity store, ConfigVersionId=1628, UserName=admin, SelectedAccessService=AuthenticateUserAPI, AcsSessionID=cisco-ise-host/435083133/112, AuthenticationMethod=PAP_ASCII, CurrentIDStoreName=Guest Users, CPMSessionID=cisco-ise-host:userauth19, Response={AuthenticationResult=UnknownUser; LdapOperationStatus=SubjectNotFound; },",
            "related": {
                "hosts": [
                    "cisco-ise-host"
                ],
                "user": [
                    "admin"
                ]
            },
            "tags": [
                "preserve_original_event"
            ],
            "user": {
                "name": "admin"
            }
        },
        {
            "@timestamp": "2022-03-03T11:37:34.931Z",
            "cisco_ise": {
                "log": {
                    "acs": {
                        "session": {
                            "id": "cisco-ise-host/435083133/126"
                        }
                    },
                    "authentication": {
                        "method": "Lookup"
                    },
                    "category": {
                        "name": "CISE_Identity_Stores_Diagnostics"
                    },
                    "config_version": {
                        "id": 1696
                    },
                    "cpm": {
                        "session": {
                            "id": "0a0009ccdD2BsLZMkW8ZRUAE/sDVf78pplxJC0wv2VwZR6N070M"
                        }
                    },
                    "message": {
                        "code": "24715",
                        "description": "External-Active-Directory: ISE has not confirmed locally previous successful machine authentication for user in Active Directory",
                        "id": "0000083416"
                    },
                    "original": {
                        "user": {
                            "name": "92-09-00-00-00-01"
                        }
                    },
                    "response": {
                        "AuthenticationResult": "UnknownUser",
                        "QueryResult": "UnknownUser"
                    },
                    "segment": {
                        "number": 0,
                        "total": 1
                    },
                    "selected": {
                        "access": {
                            "service": "Default Network Access"
                        }
                    }
                }
            },
            "ecs": {
                "version": "8.10.0"
            },
            "event": {
                "action": "external-active-directory",
                "category": [
                    "iam",
                    "authentication"
                ],
                "code": "24715",
                "kind": "event",
                "original": "\u003c183\u003eMar 3 11:37:34 cisco-ise-host CISE_Identity_Stores_Diagnostics 0000083416 1 0 2022-03-03 11:37:34.931 +00:00 0000083483 24715 DEBUG External-Active-Directory: ISE has not confirmed locally previous successful machine authentication for user in Active Directory, ConfigVersionId=1696, UserName=92-09-00-00-00-01, Protocol=Radius, OriginalUserName=92-09-00-00-00-01, AcsSessionID=cisco-ise-host/435083133/126, AuthenticationMethod=Lookup, SelectedAccessService=Default Network Access, CPMSessionID=0a0009ccdD2BsLZMkW8ZRUAE/sDVf78pplxJC0wv2VwZR6N070M, Response={AuthenticationResult=UnknownUser; QueryResult=UnknownUser; },",
                "sequence": 83483,
                "timezone": "+00:00",
                "type": [
                    "info"
                ]
            },
            "host": {
                "hostname": "cisco-ise-host"
            },
            "log": {
                "level": "debug",
                "syslog": {
                    "priority": 183,
                    "severity": {
                        "name": "debug"
                    }
                }
            },
            "message": "2022-03-03 11:37:34.931 +00:00 0000083483 24715 DEBUG External-Active-Directory: ISE has not confirmed locally previous successful machine authentication for user in Active Directory, ConfigVersionId=1696, UserName=92-09-00-00-00-01, Protocol=Radius, OriginalUserName=92-09-00-00-00-01, AcsSessionID=cisco-ise-host/435083133/126, AuthenticationMethod=Lookup, SelectedAccessService=Default Network Access, CPMSessionID=0a0009ccdD2BsLZMkW8ZRUAE/sDVf78pplxJC0wv2VwZR6N070M, Response={AuthenticationResult=UnknownUser; QueryResult=UnknownUser; },",
            "network": {
                "protocol": "radius"
            },
            "related": {
                "hosts": [
                    "cisco-ise-host"
                ],
                "user": [
                    "92-09-00-00-00-01"
                ]
            },
            "tags": [
                "preserve_original_event"
            ],
            "user": {
                "name": "92-09-00-00-00-01"
            }
        },
        {
            "@timestamp": "2022-03-10T09:05:25.669Z",
            "cisco_ise": {
                "log": {
                    "ad": {
                        "log_id": "1645524126/103"
                    },
                    "category": {
                        "name": "CISE_Identity_Stores_Diagnostics"
                    },
                    "message": {
                        "code": "24352",
                        "description": "External-Active-Directory: Identity resolution failed",
                        "id": "0000129360"
                    },
                    "segment": {
                        "number": 0,
                        "total": 1
                    }
                }
            },
            "ecs": {
                "version": "8.10.0"
            },
            "event": {
                "action": "external-active-directory",
                "category": [
                    "iam",
                    "authentication"
                ],
                "code": "24352",
                "kind": "event",
                "original": "\u003c183\u003eMar 10 09:05:25 cisco-ise-host CISE_Identity_Stores_Diagnostics 0000129360 1 0 2022-03-10 09:05:25.669 +00:00 0000129427 24352 DEBUG External-Active-Directory: Identity resolution failed,  AD-Log-Id=1645524126/103,",
                "sequence": 129427,
                "timezone": "+00:00",
                "type": [
                    "info",
                    "end"
                ]
            },
            "host": {
                "hostname": "cisco-ise-host"
            },
            "log": {
                "level": "debug",
                "syslog": {
                    "priority": 183,
                    "severity": {
                        "name": "debug"
                    }
                }
            },
            "message": "2022-03-10 09:05:25.669 +00:00 0000129427 24352 DEBUG External-Active-Directory: Identity resolution failed,  AD-Log-Id=1645524126/103,",
            "related": {
                "hosts": [
                    "cisco-ise-host"
                ]
            },
            "tags": [
                "preserve_original_event"
            ]
        },
        {
            "@timestamp": "2023-03-28T11:23:25.000Z",
            "cisco_ise": {
                "log": {
                    "acs": {
                        "session": {
                            "id": "cisco-ise-host/437837646/2"
                        }
                    },
                    "authentication": {
                        "method": "PAP_ASCII"
                    },
                    "category": {
                        "name": "CISE_Identity_Stores_Diagnostics"
                    },
                    "cpm": {
                        "session": {
                            "id": "cisco-ise-host:userauth2"
                        }
                    },
                    "currentid": {
                        "store_name": "Internal Users"
                    },
                    "message": {
                        "id": "0000000132"
                    },
                    "segment": {
                        "number": 1,
                        "total": 3
                    },
                    "selected": {
                        "access": {
                            "service": "AuthenticateUserAPI"
                        }
                    }
                }
            },
            "ecs": {
                "version": "8.10.0"
            },
            "event": {
                "kind": "event",
                "original": "\u003c183\u003eMar 28 11:23:25 cisco-ise-host CISE_Identity_Stores_Diagnostics 0000000132 3 1  SelectedAccessService=AuthenticateUserAPI, AcsSessionID=cisco-ise-host/437837646/2, AuthenticationMethod=PAP_ASCII, CurrentIDStoreName=Internal Users, CPMSessionID=cisco-ise-host:userauth2,"
            },
            "host": {
                "hostname": "cisco-ise-host"
            },
            "log": {
                "syslog": {
                    "priority": 183
                }
            },
            "message": "SelectedAccessService=AuthenticateUserAPI, AcsSessionID=cisco-ise-host/437837646/2, AuthenticationMethod=PAP_ASCII, CurrentIDStoreName=Internal Users, CPMSessionID=cisco-ise-host:userauth2,",
            "related": {
                "hosts": [
                    "cisco-ise-host"
                ]
            },
            "tags": [
                "preserve_original_event"
            ]
        }
    ]
}