---
description: Pipeline for processing self-hosted Atlassian Jira audit logs.
processors:
- set:
    field: _tmp.timestamp
    copy_from: json.timestamp
    if: ctx.json?.timestamp != null && ctx.json?.timestamp instanceof String
- set:
    field: _tmp.timestamp
    value: "{{{json.timestamp.epochSecond}}}.{{{json.timestamp.nano}}}"
    if: ctx.json?.timestamp != null && ctx.json?.timestamp instanceof Map && ctx.json?.timestamp?.epochSecond != null && ctx.json?.timestamp?.nano != null
- rename:
    field: json.author.id
    target_field: user.id
    ignore_missing: true
- rename:
    field: json.author.name
    target_field: user.name
    ignore_missing: true
- rename:
    field: json.auditType
    target_field: jira.audit.type
    ignore_missing: true
- rename:
    field: json.type
    target_field: jira.audit.type
    ignore_missing: true
- rename:
    field: json.method
    target_field: jira.audit.method
    ignore_missing: true
- rename:
    field: json.system
    target_field: service.address
    ignore_missing: true
- uri_parts:
    field: service.address
    target_field: _tmp.service
    ignore_failure: true
    if: ctx.service?.address != null
- rename:
    field: json.extraAttributes
    target_field: jira.audit.extra_attributes
    ignore_missing: true
- rename:
    field: json.changedValues
    target_field: jira.audit.changed_values
    ignore_missing: true
- rename:
    field: json.affectedObjects
    target_field: jira.audit.affected_objects
    ignore_missing: true
- set:
    field: event.action
    copy_from: jira.audit.type.actionI18nKey
    ignore_empty_value: true
- append:
    field: related.hosts
    value: '{{{_tmp.service.domain}}}'
    allow_duplicates: false
    if: ctx._tmp?.service?.domain != null
on_failure:
- set:
    field: event.kind
    value: pipeline_error
- append:
    field: error.message
    value: >
      Processor "{{{ _ingest.on_failure_processor_type }}}"
      with tag "{{{ _ingest.on_failure_processor_tag }}}"
      in pipeline "{{{ _ingest.on_failure_pipeline }}}"
      failed with message "{{{ _ingest.on_failure_message }}}"
