{
    "expected": [
        {
            "log": {
                "syslog": {
                    "priority": 7
                }
            },
            "destination": {
                "address": "rhel7.cybr.com",
                "domain": "rhel7.cybr.com"
            },
            "source": {
                "address": "10.0.0.15",
                "ip": "10.0.0.15"
            },
            "tags": [
                "preserve_original_event"
            ],
            "observer": {
                "product": "Vault",
                "hostname": "VLT01",
                "version": "12.0.0000",
                "vendor": "Cyber-Ark"
            },
            "@timestamp": "2021-03-25T12:00:08.000Z",
            "file": {
                "path": "Root\\Operating System-UnixSSH-rhel7.cybr.com-firecall2"
            },
            "ecs": {
                "version": "1.10.0"
            },
            "related": {
                "user": [
                    "PasswordManager",
                    "firecall2"
                ],
                "ip": [
                    "10.0.0.15"
                ]
            },
            "cyberarkpas": {
                "audit": {
                    "severity": "Error",
                    "reason": "ImmediateTask. Failure Description: Execution error. EXT01::A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. Error code:9002",
                    "iso_timestamp": "2021-03-25T12:00:08Z",
                    "raw": "\u003csyslog\u003e\n\n  \u003caudit_record\u003e\n    \u003cRfc5424\u003eyes\u003c/Rfc5424\u003e\n    \u003cTimestamp\u003eMar 25 08:00:08\u003c/Timestamp\u003e\n    \u003cIsoTimestamp\u003e2021-03-25T12:00:08Z\u003c/IsoTimestamp\u003e\n    \u003cHostname\u003eVLT01\u003c/Hostname\u003e\n    \u003cVendor\u003eCyber-Ark\u003c/Vendor\u003e\n    \u003cProduct\u003eVault\u003c/Product\u003e\n    \u003cVersion\u003e12.0.0000\u003c/Version\u003e\n    \u003cMessageID\u003e57\u003c/MessageID\u003e\n    \u003cDesc\u003eCPM Change Password Failed\u003c/Desc\u003e\n    \u003cSeverity\u003eError\u003c/Severity\u003e\n    \u003cIssuer\u003ePasswordManager\u003c/Issuer\u003e\n    \u003cAction\u003eCPM Change Password Failed\u003c/Action\u003e\n    \u003cSourceUser\u003e\u003c/SourceUser\u003e\n    \u003cTargetUser\u003e\u003c/TargetUser\u003e\n    \u003cSafe\u003eLinux Accounts\u003c/Safe\u003e\n    \u003cFile\u003eRoot\\Operating System-UnixSSH-rhel7.cybr.com-firecall2\u003c/File\u003e\n    \u003cStation\u003e10.0.0.15\u003c/Station\u003e\n    \u003cLocation\u003e\u003c/Location\u003e\n    \u003cCategory\u003e\u003c/Category\u003e\n    \u003cRequestId\u003e\u003c/RequestId\u003e\n    \u003cReason\u003eImmediateTask. Failure Description: Execution error. EXT01::A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. Error code:9002\u003c/Reason\u003e\n    \u003cExtraDetails\u003eaddress=rhel7.cybr.com;username=firecall2;\u003c/ExtraDetails\u003e\n    \u003cMessage\u003eCPM Change Password Failed\u003c/Message\u003e\n    \u003cGatewayStation\u003e\u003c/GatewayStation\u003e\n    \u003cCAProperties\u003e\n      \u003cCAProperty Name=\"PolicyID\" Value=\"UnixSSH\"\u003e\u003c/CAProperty\u003e\n      \u003cCAProperty Name=\"UserName\" Value=\"firecall2\"\u003e\u003c/CAProperty\u003e\n      \u003cCAProperty Name=\"Address\" Value=\"rhel7.cybr.com\"\u003e\u003c/CAProperty\u003e\n      \u003cCAProperty Name=\"DeviceType\" Value=\"Operating System\"\u003e\u003c/CAProperty\u003e\n      \u003cCAProperty Name=\"ResetImmediately\" Value=\"ChangeTask\"\u003e\u003c/CAProperty\u003e\n      \u003cCAProperty Name=\"CPMStatus\" Value=\"failure\"\u003e\u003c/CAProperty\u003e\n      \u003cCAProperty Name=\"ExtraPass3Name\" Value=\"Operating System-UnixSSH-rhel7.cybr.com-root\"\u003e\u003c/CAProperty\u003e\n      \u003cCAProperty Name=\"ExtraPass3Folder\" Value=\"Root\"\u003e\u003c/CAProperty\u003e\n      \u003cCAProperty Name=\"ExtraPass3Safe\" Value=\"Linux Root\"\u003e\u003c/CAProperty\u003e\n      \u003cCAProperty Name=\"RetriesCount\" Value=\"0\"\u003e\u003c/CAProperty\u003e\n      \u003cCAProperty Name=\"LastFailDate\" Value=\"1616673608\"\u003e\u003c/CAProperty\u003e\n      \u003cCAProperty Name=\"LastTask\" Value=\"ChangeTask\"\u003e\u003c/CAProperty\u003e\n      \u003cCAProperty Name=\"LastSuccessVerification\" Value=\"1616580255\"\u003e\u003c/CAProperty\u003e\n      \u003cCAProperty Name=\"CPMErrorDetails\" Value=\"Execution error. EXT01::A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. Error code:9002\"\u003e\u003c/CAProperty\u003e\n      \u003cCAProperty Name=\"CreationMethod\" Value=\"PVWA\"\u003e\u003c/CAProperty\u003e\n      \u003cCAProperty Name=\"LastSuccessChange\" Value=\"1616011989\"\u003e\u003c/CAProperty\u003e\n      \u003cCAProperty Name=\"LastSuccessReconciliation\" Value=\"1576120341\"\u003e\u003c/CAProperty\u003e\n      \u003cCAProperty Name=\"UseSudoOnReconcile\" Value=\"No\"\u003e\u003c/CAProperty\u003e\n      \u003cCAProperty Name=\"Tags\" Value=\"SSH\"\u003e\u003c/CAProperty\u003e\n      \u003cCAProperty Name=\"Privcloud\" Value=\"privcloud\"\u003e\u003c/CAProperty\u003e\n    \u003c/CAProperties\u003e\n  \u003c/audit_record\u003e\n\n\u003c/syslog\u003e",
                    "message": "CPM Change Password Failed",
                    "issuer": "PasswordManager",
                    "extra_details": {
                        "other": {
                            "address": "rhel7.cybr.com"
                        },
                        "username": "firecall2"
                    },
                    "rfc5424": true,
                    "ca_properties": {
                        "privcloud": "privcloud",
                        "other": {
                            "extra_pass3_name": "Operating System-UnixSSH-rhel7.cybr.com-root",
                            "extra_pass3_folder": "Root",
                            "use_sudo_on_reconcile": "No",
                            "extra_pass3_safe": "Linux Root"
                        },
                        "address": "rhel7.cybr.com",
                        "creation_method": "PVWA",
                        "cpm_status": "failure",
                        "policy_id": "UnixSSH",
                        "last_success_reconciliation": "1576120341",
                        "user_name": "firecall2",
                        "device_type": "Operating System",
                        "retries_count": "0",
                        "last_success_verification": "1616580255",
                        "reset_immediately": "ChangeTask",
                        "last_task": "ChangeTask",
                        "tags": "SSH",
                        "cpm_error_details": "Execution error. EXT01::A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. Error code:9002",
                        "last_fail_date": "1616673608",
                        "last_success_change": "1616011989"
                    },
                    "file": "Root\\Operating System-UnixSSH-rhel7.cybr.com-firecall2",
                    "safe": "Linux Accounts",
                    "station": "10.0.0.15",
                    "action": "CPM Change Password Failed",
                    "timestamp": "Mar 25 08:00:08",
                    "desc": "CPM Change Password Failed"
                }
            },
            "host": {
                "name": "VLT01"
            },
            "event": {
                "severity": 7,
                "reason": "Execution error. EXT01::A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. Error code:9002",
                "ingested": "2021-06-09T10:24:36.068992600Z",
                "original": "\u003c7\u003e1 2021-03-25T12:00:08Z VLT01 {\"format\":\"elastic\",\"version\":\"1.0\",\"raw\":\"\u003csyslog\u003e\\n\\n  \u003caudit_record\u003e\\n    \u003cRfc5424\u003eyes\u003c/Rfc5424\u003e\\n    \u003cTimestamp\u003eMar 25 08:00:08\u003c/Timestamp\u003e\\n    \u003cIsoTimestamp\u003e2021-03-25T12:00:08Z\u003c/IsoTimestamp\u003e\\n    \u003cHostname\u003eVLT01\u003c/Hostname\u003e\\n    \u003cVendor\u003eCyber-Ark\u003c/Vendor\u003e\\n    \u003cProduct\u003eVault\u003c/Product\u003e\\n    \u003cVersion\u003e12.0.0000\u003c/Version\u003e\\n    \u003cMessageID\u003e57\u003c/MessageID\u003e\\n    \u003cDesc\u003eCPM Change Password Failed\u003c/Desc\u003e\\n    \u003cSeverity\u003eError\u003c/Severity\u003e\\n    \u003cIssuer\u003ePasswordManager\u003c/Issuer\u003e\\n    \u003cAction\u003eCPM Change Password Failed\u003c/Action\u003e\\n    \u003cSourceUser\u003e\u003c/SourceUser\u003e\\n    \u003cTargetUser\u003e\u003c/TargetUser\u003e\\n    \u003cSafe\u003eLinux Accounts\u003c/Safe\u003e\\n    \u003cFile\u003eRoot\\\\Operating System-UnixSSH-rhel7.cybr.com-firecall2\u003c/File\u003e\\n    \u003cStation\u003e10.0.0.15\u003c/Station\u003e\\n    \u003cLocation\u003e\u003c/Location\u003e\\n    \u003cCategory\u003e\u003c/Category\u003e\\n    \u003cRequestId\u003e\u003c/RequestId\u003e\\n    \u003cReason\u003eImmediateTask. Failure Description: Execution error. EXT01::A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. Error code:9002\u003c/Reason\u003e\\n    \u003cExtraDetails\u003eaddress=rhel7.cybr.com;username=firecall2;\u003c/ExtraDetails\u003e\\n    \u003cMessage\u003eCPM Change Password Failed\u003c/Message\u003e\\n    \u003cGatewayStation\u003e\u003c/GatewayStation\u003e\\n    \u003cCAProperties\u003e\\n      \u003cCAProperty Name=\\\"PolicyID\\\" Value=\\\"UnixSSH\\\"\u003e\u003c/CAProperty\u003e\\n      \u003cCAProperty Name=\\\"UserName\\\" Value=\\\"firecall2\\\"\u003e\u003c/CAProperty\u003e\\n      \u003cCAProperty Name=\\\"Address\\\" Value=\\\"rhel7.cybr.com\\\"\u003e\u003c/CAProperty\u003e\\n      \u003cCAProperty Name=\\\"DeviceType\\\" Value=\\\"Operating System\\\"\u003e\u003c/CAProperty\u003e\\n      \u003cCAProperty Name=\\\"ResetImmediately\\\" Value=\\\"ChangeTask\\\"\u003e\u003c/CAProperty\u003e\\n      \u003cCAProperty Name=\\\"CPMStatus\\\" Value=\\\"failure\\\"\u003e\u003c/CAProperty\u003e\\n      \u003cCAProperty Name=\\\"ExtraPass3Name\\\" Value=\\\"Operating System-UnixSSH-rhel7.cybr.com-root\\\"\u003e\u003c/CAProperty\u003e\\n      \u003cCAProperty Name=\\\"ExtraPass3Folder\\\" Value=\\\"Root\\\"\u003e\u003c/CAProperty\u003e\\n      \u003cCAProperty Name=\\\"ExtraPass3Safe\\\" Value=\\\"Linux Root\\\"\u003e\u003c/CAProperty\u003e\\n      \u003cCAProperty Name=\\\"RetriesCount\\\" Value=\\\"0\\\"\u003e\u003c/CAProperty\u003e\\n      \u003cCAProperty Name=\\\"LastFailDate\\\" Value=\\\"1616673608\\\"\u003e\u003c/CAProperty\u003e\\n      \u003cCAProperty Name=\\\"LastTask\\\" Value=\\\"ChangeTask\\\"\u003e\u003c/CAProperty\u003e\\n      \u003cCAProperty Name=\\\"LastSuccessVerification\\\" Value=\\\"1616580255\\\"\u003e\u003c/CAProperty\u003e\\n      \u003cCAProperty Name=\\\"CPMErrorDetails\\\" Value=\\\"Execution error. EXT01::A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. Error code:9002\\\"\u003e\u003c/CAProperty\u003e\\n      \u003cCAProperty Name=\\\"CreationMethod\\\" Value=\\\"PVWA\\\"\u003e\u003c/CAProperty\u003e\\n      \u003cCAProperty Name=\\\"LastSuccessChange\\\" Value=\\\"1616011989\\\"\u003e\u003c/CAProperty\u003e\\n      \u003cCAProperty Name=\\\"LastSuccessReconciliation\\\" Value=\\\"1576120341\\\"\u003e\u003c/CAProperty\u003e\\n      \u003cCAProperty Name=\\\"UseSudoOnReconcile\\\" Value=\\\"No\\\"\u003e\u003c/CAProperty\u003e\\n      \u003cCAProperty Name=\\\"Tags\\\" Value=\\\"SSH\\\"\u003e\u003c/CAProperty\u003e\\n      \u003cCAProperty Name=\\\"Privcloud\\\" Value=\\\"privcloud\\\"\u003e\u003c/CAProperty\u003e\\n    \u003c/CAProperties\u003e\\n  \u003c/audit_record\u003e\\n\\n\u003c/syslog\u003e\",\"syslog\":{\"audit_record\":{\"Rfc5424\":\"yes\",\"Timestamp\":\"Mar 25 08:00:08\",\"IsoTimestamp\":\"2021-03-25T12:00:08Z\",\"Hostname\":\"VLT01\",\"Vendor\":\"Cyber-Ark\",\"Product\":\"Vault\",\"Version\":\"12.0.0000\",\"MessageID\":\"57\",\"Desc\":\"CPM Change Password Failed\",\"Severity\":\"Error\",\"Issuer\":\"PasswordManager\",\"Action\":\"CPM Change Password Failed\",\"SourceUser\":\"\",\"TargetUser\":\"\",\"Safe\":\"Linux Accounts\",\"File\":\"Root\\\\Operating System-UnixSSH-rhel7.cybr.com-firecall2\",\"Station\":\"10.0.0.15\",\"Location\":\"\",\"Category\":\"\",\"RequestId\":\"\",\"Reason\":\"ImmediateTask. Failure Description: Execution error. EXT01::A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. Error code:9002\",\"ExtraDetails\":\"address=rhel7.cybr.com;username=firecall2;\",\"Message\":\"CPM Change Password Failed\",\"GatewayStation\":\"\",\"CAProperties\":{\"CAProperty\":[{\"Name\":\"PolicyID\",\"Value\":\"UnixSSH\"},{\"Name\":\"UserName\",\"Value\":\"firecall2\"},{\"Name\":\"Address\",\"Value\":\"rhel7.cybr.com\"},{\"Name\":\"DeviceType\",\"Value\":\"Operating System\"},{\"Name\":\"ResetImmediately\",\"Value\":\"ChangeTask\"},{\"Name\":\"CPMStatus\",\"Value\":\"failure\"},{\"Name\":\"ExtraPass3Name\",\"Value\":\"Operating System-UnixSSH-rhel7.cybr.com-root\"},{\"Name\":\"ExtraPass3Folder\",\"Value\":\"Root\"},{\"Name\":\"ExtraPass3Safe\",\"Value\":\"Linux Root\"},{\"Name\":\"RetriesCount\",\"Value\":\"0\"},{\"Name\":\"LastFailDate\",\"Value\":\"1616673608\"},{\"Name\":\"LastTask\",\"Value\":\"ChangeTask\"},{\"Name\":\"LastSuccessVerification\",\"Value\":\"1616580255\"},{\"Name\":\"CPMErrorDetails\",\"Value\":\"Execution error. EXT01::A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. Error code:9002\"},{\"Name\":\"CreationMethod\",\"Value\":\"PVWA\"},{\"Name\":\"LastSuccessChange\",\"Value\":\"1616011989\"},{\"Name\":\"LastSuccessReconciliation\",\"Value\":\"1576120341\"},{\"Name\":\"UseSudoOnReconcile\",\"Value\":\"No\"},{\"Name\":\"Tags\",\"Value\":\"SSH\"},{\"Name\":\"Privcloud\",\"Value\":\"privcloud\"}]}}}}",
                "code": "57",
                "kind": "event",
                "action": "cpm change password failed",
                "type": [
                    "user",
                    "change",
                    "error"
                ],
                "category": [
                    "iam"
                ],
                "outcome": "failure"
            },
            "user": {
                "name": "PasswordManager",
                "target": {
                    "name": "firecall2"
                }
            }
        }
    ]
}